name: ci

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - 
        name: Build dockerfile (with push)
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm --output "type=image,push=true" --file ./Dockerfile . --build-arg IMAGE_TAG=latest --tag dyrnq/registry:latest
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm --output "type=image,push=true" --file ./Dockerfile . --build-arg IMAGE_TAG=2 --tag dyrnq/registry:2
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm --output "type=image,push=true" --file ./Dockerfile . --build-arg IMAGE_TAG=2.7 --tag dyrnq/registry:2.7
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm --output "type=image,push=true" --file ./Dockerfile . --build-arg IMAGE_TAG=2.6 --tag dyrnq/registry:2.6
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm --output "type=image,push=true" --file ./Dockerfile . --build-arg IMAGE_TAG=2.7.1 --tag dyrnq/registry:2.7.1
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm --output "type=image,push=true" --file ./Dockerfile . --build-arg IMAGE_TAG=2.6.2 --tag dyrnq/registry:2.6.2